services:
  duyi-monitor-clickhouse:
    image: bitnami/clickhouse:25.5.2
    container_name: duyi-monitor-clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: 123456
      CLICKHOUSE_DATABASE: default
  duyi-monitor-postgres:
    image: bitnami/postgresql:17.5.0
    container_name: duyi-monitor-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=postgres
    volumes:
      - ./postgresql_data:/bitnami/postgresql
networks:
  default:
    name: duyi-monitor-network
    driver: bridge 
